version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.1.2
  aws-ecs: circleci/aws-ecs@3.0.0
executors:
  nodejs:
    description: |
      Node 14.17.6 runtime environment
    docker:
    - image: circleci/node:14.17.6
jobs:
  install:
    description: install dependencies
    executor: nodejs
    steps:
      - checkout
      - restore_cache:
          key: 'v1-node-modules-{{ checksum "package-lock.json" }}'
      - run: npm install
      - save_cache:
          key: 'v1-node-modules-{{ checksum "package-lock.json" }}'
          paths:
            - ~/project/node_modules
      - persist_to_workspace:
          paths:
            - project
          root: ~/
workflows:
  build-and-deploy:
    jobs:
      - install:
          filters:
            branches:
              only:
                - main
          name: install dependencies
      - aws-ecr/build-and-push-image:
          requires:
            - install dependencies
          attach-workspace: true
          workspace-root: ~/
          repo: chat-server
          filters:
            branches:
              only:
                - main
          name: build and push image
      - aws-ecs/deploy-service-update:
          requires:
            - build and push image
          cluster: bonvih-cluster 
          family: chatserver_task 
          service-name: chat_service 
          force-new-deployment: true
          filters:
            branches:
              only:
                - main
          name: force deployment
